apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dialogflow-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dialogflow-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: dialogflow-ui
    spec:
      containers:
      - name: dialogflow-ui
        image: docker.pkg.github.com/mishushakov/dialogflow-web-v2/dialogflow-web-v2
        imagePullPolicy: Always