apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dialogflow-ui
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: ushacom
spec:
  rules:
  - host: '*.ui.dialogflow.cloud.ushakov.co'
    http:
      paths:
      - path: /
        backend:
          serviceName: dialogflow-ui
          servicePort: http
  tls:
  - hosts:
    - '*.ui.dialogflow.cloud.ushakov.co'
    secretName: dialogflow-ui-cert